// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItems(arg1, arg2) {
  return window['go']['main']['App']['AddItems'](arg1, arg2);
}

export function AddKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddKey'](arg1, arg2, arg3);
}

export function AddPlayer(arg1) {
  return window['go']['main']['App']['AddPlayer'](arg1);
}

export function AddPlayerToWhitelist(arg1, arg2) {
  return window['go']['main']['App']['AddPlayerToWhitelist'](arg1, arg2);
}

export function AddSteamId(arg1) {
  return window['go']['main']['App']['AddSteamId'](arg1);
}

export function AddToSafehouse(arg1) {
  return window['go']['main']['App']['AddToSafehouse'](arg1);
}

export function AddVehicle(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddVehicle'](arg1, arg2, arg3);
}

export function AddXp(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddXp'](arg1, arg2, arg3);
}

export function Alarm() {
  return window['go']['main']['App']['Alarm']();
}

export function BanIp(arg1) {
  return window['go']['main']['App']['BanIp'](arg1);
}

export function BanSteamId(arg1) {
  return window['go']['main']['App']['BanSteamId'](arg1);
}

export function BanUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['BanUsers'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckModsNeedUpdate() {
  return window['go']['main']['App']['CheckModsNeedUpdate']();
}

export function ChooseSandboxPathDialog(arg1) {
  return window['go']['main']['App']['ChooseSandboxPathDialog'](arg1);
}

export function Chopper() {
  return window['go']['main']['App']['Chopper']();
}

export function ConnectRcon(arg1) {
  return window['go']['main']['App']['ConnectRcon'](arg1);
}

export function CopyToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyToClipboard'](arg1, arg2);
}

export function CreateHorde(arg1, arg2) {
  return window['go']['main']['App']['CreateHorde'](arg1, arg2);
}

export function CreateHorde2(arg1, arg2) {
  return window['go']['main']['App']['CreateHorde2'](arg1, arg2);
}

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function DisconnectRcon() {
  return window['go']['main']['App']['DisconnectRcon']();
}

export function ExportOptionsDialog(arg1) {
  return window['go']['main']['App']['ExportOptionsDialog'](arg1);
}

export function Format(arg1, arg2) {
  return window['go']['main']['App']['Format'](arg1, arg2);
}

export function GetArch() {
  return window['go']['main']['App']['GetArch']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetOs() {
  return window['go']['main']['App']['GetOs']();
}

export function GetUpdateSource() {
  return window['go']['main']['App']['GetUpdateSource']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GodMode(arg1, arg2) {
  return window['go']['main']['App']['GodMode'](arg1, arg2);
}

export function Gunshot() {
  return window['go']['main']['App']['Gunshot']();
}

export function ImportOptionsDialog() {
  return window['go']['main']['App']['ImportOptionsDialog']();
}

export function InvisiblePlayers(arg1, arg2) {
  return window['go']['main']['App']['InvisiblePlayers'](arg1, arg2);
}

export function IsRconConnected() {
  return window['go']['main']['App']['IsRconConnected']();
}

export function KickFromSafehouse(arg1) {
  return window['go']['main']['App']['KickFromSafehouse'](arg1);
}

export function KickUsers(arg1, arg2) {
  return window['go']['main']['App']['KickUsers'](arg1, arg2);
}

export function Lightning(arg1) {
  return window['go']['main']['App']['Lightning'](arg1);
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function LoadItemsDialog() {
  return window['go']['main']['App']['LoadItemsDialog']();
}

export function LoadMessageDialog() {
  return window['go']['main']['App']['LoadMessageDialog']();
}

export function NoClipPlayers(arg1, arg2) {
  return window['go']['main']['App']['NoClipPlayers'](arg1, arg2);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function Players() {
  return window['go']['main']['App']['Players']();
}

export function RandomLightning() {
  return window['go']['main']['App']['RandomLightning']();
}

export function RandomThunder() {
  return window['go']['main']['App']['RandomThunder']();
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function ReadSandboxVars() {
  return window['go']['main']['App']['ReadSandboxVars']();
}

export function ReleaseSafehouse() {
  return window['go']['main']['App']['ReleaseSafehouse']();
}

export function ReloadAllLua() {
  return window['go']['main']['App']['ReloadAllLua']();
}

export function ReloadLua(arg1) {
  return window['go']['main']['App']['ReloadLua'](arg1);
}

export function ReloadOptions() {
  return window['go']['main']['App']['ReloadOptions']();
}

export function RemoveItems(arg1) {
  return window['go']['main']['App']['RemoveItems'](arg1);
}

export function RemoveMapSymbolsForUser(arg1) {
  return window['go']['main']['App']['RemoveMapSymbolsForUser'](arg1);
}

export function RemovePlayersFromWhitelist(arg1, arg2) {
  return window['go']['main']['App']['RemovePlayersFromWhitelist'](arg1, arg2);
}

export function RemoveSteamId(arg1) {
  return window['go']['main']['App']['RemoveSteamId'](arg1);
}

export function RemoveZombies() {
  return window['go']['main']['App']['RemoveZombies']();
}

export function RestartApplication(arg1) {
  return window['go']['main']['App']['RestartApplication'](arg1);
}

export function SandboxAccess() {
  return window['go']['main']['App']['SandboxAccess']();
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SaveCredentials(arg1) {
  return window['go']['main']['App']['SaveCredentials'](arg1);
}

export function SaveItemsDialog(arg1) {
  return window['go']['main']['App']['SaveItemsDialog'](arg1);
}

export function SaveMessagesDialog(arg1) {
  return window['go']['main']['App']['SaveMessagesDialog'](arg1);
}

export function SaveSandboxVars(arg1) {
  return window['go']['main']['App']['SaveSandboxVars'](arg1);
}

export function SaveWorld() {
  return window['go']['main']['App']['SaveWorld']();
}

export function SendNotification(arg1) {
  return window['go']['main']['App']['SendNotification'](arg1);
}

export function SendRconCommand(arg1) {
  return window['go']['main']['App']['SendRconCommand'](arg1);
}

export function SendWindowsNotification(arg1) {
  return window['go']['main']['App']['SendWindowsNotification'](arg1);
}

export function ServerMsg(arg1) {
  return window['go']['main']['App']['ServerMsg'](arg1);
}

export function ServerOptions() {
  return window['go']['main']['App']['ServerOptions']();
}

export function SetAccessLevel(arg1, arg2) {
  return window['go']['main']['App']['SetAccessLevel'](arg1, arg2);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function SetLogLevel(arg1, arg2) {
  return window['go']['main']['App']['SetLogLevel'](arg1, arg2);
}

export function SetSandboxAccess(arg1, arg2) {
  return window['go']['main']['App']['SetSandboxAccess'](arg1, arg2);
}

export function SetStats(arg1, arg2) {
  return window['go']['main']['App']['SetStats'](arg1, arg2);
}

export function SetUserPassword(arg1, arg2) {
  return window['go']['main']['App']['SetUserPassword'](arg1, arg2);
}

export function StartRain(arg1) {
  return window['go']['main']['App']['StartRain'](arg1);
}

export function StartStorm(arg1) {
  return window['go']['main']['App']['StartStorm'](arg1);
}

export function StopRain() {
  return window['go']['main']['App']['StopRain']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopWeather() {
  return window['go']['main']['App']['StopWeather']();
}

export function TeleportPlayerToPlayer(arg1, arg2) {
  return window['go']['main']['App']['TeleportPlayerToPlayer'](arg1, arg2);
}

export function TeleportToCoordinates(arg1, arg2) {
  return window['go']['main']['App']['TeleportToCoordinates'](arg1, arg2);
}

export function Thunder(arg1) {
  return window['go']['main']['App']['Thunder'](arg1);
}

export function UnbanIp(arg1) {
  return window['go']['main']['App']['UnbanIp'](arg1);
}

export function UnbanSteamId(arg1) {
  return window['go']['main']['App']['UnbanSteamId'](arg1);
}

export function UnbanUsers(arg1) {
  return window['go']['main']['App']['UnbanUsers'](arg1);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}

export function UpdateOptions(arg1, arg2) {
  return window['go']['main']['App']['UpdateOptions'](arg1, arg2);
}

export function VoiceBanPlayers(arg1, arg2) {
  return window['go']['main']['App']['VoiceBanPlayers'](arg1, arg2);
}

export function WorldGen(arg1) {
  return window['go']['main']['App']['WorldGen'](arg1);
}

export function WorldGenStatus() {
  return window['go']['main']['App']['WorldGenStatus']();
}
